### ISSUE TITLE
High CPU + (extremely) high GPU usage?

### ISSUE THREAD

**Issue by chhallchase** [gracejohnsn/NumberPrime#5]
Unsure if there is a memory link; the site is using 100% of my GPU (940Mx) and about 40-50% of my CPU.
This is on chrome;
https://numberprime-b359d.firebaseapp.com/#!/Settings This is the page.

This doesn't happen while logging in as a teacher

pc hardware: 
i5-6200U 2.3GHz
GeForce 940MX
Windows 10

**Comment by chhallchase** [comment]
I think this was due to my long username extending the screen and then creating a lot of screen space for webgl to display - causing the gpu usage. Upon reloading the page, the gpu usage is only ~70 percent and not freezing my pc

**Comment by chhallchase** [comment]
Upon further testing - I don't believe it is due to the username; the GPU lag picks up once i've done multiple different exercises which may be a memory leak or the webgl from those exercises continually running even when the exercise is finished.

**Comment by DonoStevenson** [comment]
The problem sets were creating another loop of the problem set drawing code each time it was loaded, added a check for this so hopefully that solves it.
